# Dockerfile for Streamlit
FROM python:3.10-slim

WORKDIR /app

COPY requirements_streamlit.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements_streamlit.txt

COPY . .

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]